#!/bin/bash

if [[ "$EUID" -ne 0 ]]
    then echo "[Taos] Please run as root."
    exit 1
fi

if [[ $1 == "start" ]]; then
    systemctl start taos
    exit
elif [[ $1 == "stop" ]]; then
    systemctl stop taos
    exit
else
    echo "taos <command>"
    echo ""
    echo "Usage:"
    echo ""
    echo "taos start  start taos daemon"
    echo "taos stop   stop taos daemon"
    exit 1
fi
